apiVersion: v1
kind: Pod
metadata:
  name: ankit-demo
  namespace: apos-demo
  labels:
    app: ankit-demo
    version: v1
spec:
  containers:
  - image: registry.apos.in/ankit/concert-angular
    name: concert-angular
    ports:
      - containerPort: 80
        name: http
  restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: ankit-demo-service
  namespace: apos-demo
spec:
  selector:
    app: ankit-demo
  ports:
  - name: http-service
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ankit-demo
  namespace: apos-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 700m
spec:
  rules:
  - host: ankit-demo.apos.in
    http:
      paths:
      - backend:
          serviceName: ankit-demo-service
          servicePort: http-service
        path: /

